erastriya/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
# from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('auth/', include('django.contrib.auth.urls')),  # include auth URLs
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('',include('home.urls', namespace="home")),
    path('post/',include('post.urls',namespace="post")),
    # path('sitemap.xml/', serve, {'document_root': settings.STATICFILES_DIRS[0], 'path': 'sitemap.xml'}),
    # path('robots.txt/', serve, {'document_root': settings.STATICFILES_DIRS[0], 'path': 'robots.txt'}),



]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home.views import home_page,about_view,contact_view,advertisement_view
app_name = "home"
urlpatterns = [
    path('',home_page,name="home_page"),
    path('about/',about_view,name="about"),
    path('contact/',contact_view,name="contact"),
    path('advertisement-info/',advertisement_view,name="advertisement_info"),
]

post/urls.py
from django.urls import path
from post.views import (
    politics_view, news_view, law_view, sports_view, 
    education_view, detail_view, search_result,
    other_view, international_view, business_view,
    scienceandtech_view, entertainment_view, economy_view, 
    literature_view, religion_culture_view, capital_market_view
    
)

app_name = "post"
urlpatterns = [
    path('politics/',politics_view,name="politics"),
    path('news/',news_view,name="news"),
    path('law/',law_view,name="law"),
    path('sports/',sports_view,name="sports"),
    path('education/',education_view,name="education"),
    path('international/',international_view,name="international"),
    path('business/',business_view,name="business"),
    path('economy/',economy_view,name="economy"),
    path('entertainment/',entertainment_view,name="entertainment"),
    path('science-technology/',scienceandtech_view,name="scienceandtech"),
    path('literature/',literature_view,name="literature"),
    path('religion-culture/',religion_culture_view,name="religion_culture"),
    path('capital-market/',capital_market_view,name="capital_market"),
    path('post-detail/<int:id>/',detail_view,name="detail"),
    path('search/',search_result,name="search_result"),

    
]

home/models.py
from django.db import models

home/views.py
from django.shortcuts import render
from post.models import Category,Status,Post,Home_content
from post.utils import get_or_none

def home_page(request):
    posts = Post.objects.filter(status=Status.PUBLISH).order_by('-created_at')
    main_content = Post.objects.filter(status=Status.PUBLISH,home_content=Home_content.YES).order_by('-created_at')[:1]
    print(main_content)
    politics  = Post.objects.filter(status=Status.PUBLISH,home_content=Home_content.NO,category=Category.objects.get(category='politics')).order_by('-created_at')[:6]
    news  = Post.objects.filter(status=Status.PUBLISH,home_content=Home_content.NO,category=Category.objects.get(category='news')).order_by('-created_at')[:6]
    laws  = Post.objects.filter(status=Status.PUBLISH,home_content=Home_content.NO,category=Category.objects.get(category='laws')).order_by('-created_at')[:6]
    sports  = Post.objects.filter(status=Status.PUBLISH,home_content=Home_content.NO,category=Category.objects.get(category='sports')).order_by('-created_at')[:6]
    education  = Post.objects.filter(status=Status.PUBLISH,home_content=Home_content.NO,category=Category.objects.get(category='education')).order_by('-created_at')[:6]


    context = {"posts": posts,"politics":politics,"news":news,"laws":laws,"sports":sports,"education":education,"main_content":main_content}
    return render(request,"index.html",context)



def about_view(request):
    return render(request,"about.html")


def get_latest_func():
    from post.views import func_post
    return func_post()



def advertisement_view(request):
    latest_func = get_latest_func()

    return render(request,"advertisement.html",{"posts":latest_func})




def contact_view(request):
    latest_func = get_latest_func()

    return render(request,"contact.html",{"posts":latest_func})

home/templates/about.html
{% extends 'base_html.html' %}
{% load static %}
{% block maincontent %}


<Section class="container mt-3 p-3">

    <h1 class="fs-2 static-title">About Us</h1>
    <div class="my-4">
        <p class="text-secondary about-text lh-lg">ईराष्ट्रिय मिडिया हाउस  प्रा. लि. द्वारा संचालित <a href="/" class="footer-links">Erastriya.com</a> बहु भाषामा प्रकाशित हुने डिजिटल अनलाइन पत्रिका हो । ईराष्ट्रिय मिडिया हाउस प्रा. लि. दर्ता नं 4651 मा सूचना बिभागमा दर्ता छ। तपाईंसँग कुनै लेख, रचना, विचार, सूचना, समाचार, अनियमितता तथा भ्रष्टचार सम्बन्धी र अन्य कुनै भिडियो छन भने erastriyamediahouse1@gmail.com मा पठाउन सक्नुहुनेछ । तपाईंका सामग्रीलाई हामी प्राथमिकताका साथ प्रकाशित गर्नेछौं ।</p>
        
    </div>
</Section>


{% endblock maincontent %}

home/templates/advertisement.html
{% extends 'base_html.html' %}
{% load static %}
{% block maincontent %}



<section class="container my-4 pb-4">

    <section class="row">

        <section class="col-lg-8 col-md-6 col-sm-12">

            <h1 class="fs-2 static-title">For Advertisement</h1>
            <div class="py-4">
                <h3 class="fs-5">Address: </h3>
        
                <span>
                    Anamnagar,Kathmandu
                </span>
            </div>
            <div class="py-4">
                <h3 class="fs-5">Contact Details: </h3>
                <p class="mt-3 mb-0">Mobile No: 9763445775, 9809563557</p>
                <p>Email: aderastriya5@gmail.com</p>
        
        
            </div>
    
    
    
        </section>
    
        <section class="col-lg-4 col-md-6 col-sm-12">
                    <!-- list of latest taja update  -->
    
                    <div style="max-width:100%; ">
    
    
       
                        <!-- advertisememt details page -->
                        {% comment %} <div class="latest-ads py1">
                          <img src="{{ url '' }}" width="100%" />
                        </div> {% endcomment %}
          
                        <!-- end of details page advertisement -->
                        <div class="news-list-1 mt-3">{% include 'latestnews.html' %}</div>
                    </div>
            
        </section>


    </section>







</section>



{% endblock maincontent %}

home/templates/contact.html
{% extends 'base_html.html' %}
{% load static %}
{% block maincontent %}



<section class="container my-4 pb-4 ">

    <section class="row">

        <section class="col-lg-8 col-md-6 col-sm-12">

            <h1 class="fs-2 static-title">Contact Us</h1>
            <div class="py-3">
         
               <p class="mb-0">Erastriya Media House</p> 


                <p class="mb-0">
                    Anamnagar,Kathmandu
                </p>

                <p class="mb-0">Mobile No: 9763445775, 9809563557</p>
                <p>Email: erastriyamediahouse1@gmail.com

                </p>

            </div>
        
        
    
    
    
        </section>
    
        <section class="col-lg-4 col-md-6 col-sm-12">
                    <!-- list of latest taja update  -->
    
                    <div style="max-width:100%; ">
    
    
       
                        <!-- advertisememt details page -->
                        {% comment %} <div class="latest-ads py1">
                          <img src="{{ url '' }}" width="100%" />
                        </div> {% endcomment %}
          
                        <!-- end of details page advertisement -->
                        <div class="news-list-1 mt-3">{% include 'latestnews.html' %}</div>
                    </div>
            
        </section>


    </section>







</section>



{% endblock maincontent %}

home/templates/index.html
{% extends 'base_html.html' %}

{% load static %}
{% load nepalidatetime %}
{% block meta_tags %}
  <meta property="og:type" content="article">
  <meta name="subject" content="erastriya">
  <meta name="publisher" content="erastriya">  
{% endblock %}
{% block maincontent %}
{% comment %} {% load my_filters %} {% endcomment %}

<div class="container">

    <!-- Banner news -->
    <section class="block1 my-4">
          <div class="container">
              <div class="box-1">
                      {% comment %} <div class="advertisement text-center pb-3">
                        <img src="{% static 'images/add1.gif' %}"/>
                      </div> {% endcomment %}
                      {% if main_content %}
                      <div class="banner py">
                        {% for home_content in main_content|slice:":1"%}
                        <a href="{% url 'post:detail' home_content.id %}">
                          <h2 class="front-header">{{home_content.title}}</h2>
                        </a>
                        {% comment %} <h2 class="front-header">{{home_content.title}}</h2> {% endcomment %}
                          
                          {% comment %} <div class="author py"><h4 class="text-danger">- Erastriya</h4></div> {% endcomment %}
                          {% if home_content.image %}
                          <a href="{% url 'post:detail' home_content.id %}">
                          <img class="img-fluid mt-4 main-img" src="{{ home_content.image.url }}" alt="{{home_content.title}}"/>
                        </a>

                          {% endif %}
                          {% endfor %}


                      </div> 
                      {% endif %}
                </div>
            </div>
    </section>


    {% comment %}  Samachar {% endcomment %}


    <section class="block2 py-4">
    <div class="container">
        <div class="items-content ">
          {% if news %}
            <div class="main-article" >

              <h3 class="text-color">समाचार</h3>
              <div class="first-news py-3 row row-cols-1 row-cols-sm-1 row-cols-md-2 row-cols-lg-3">
                      {% for samachar in news|slice:":6" %}

                      <div class="col">                                   
                        <div class="card common-card border-0">
                          <a href="{% url 'post:detail' samachar.id %}" class="stretched-link"></a>
                          {% if samachar.image %}
                          <img src="{{ samachar.image.url }}" class="card-img-bottom card-img-size img-fluid" alt="{{samachar.title}}">
                          {% endif %}
                          <div class="p-2">
                          <div class="card-title text-card">{{ samachar.title }}</div>
                          {% load tz %}
                          <small class="text-muted">
                            {{ samachar.created_at|nepalihumanize:86400 }}
                          </small>

                          </div>

                        </div>
                      
                      </div>
                      {% endfor %}
                      
              </div>
                    
   
              </div>
            {% endif %}
          <div class="side-news px-2">
            {% include 'latestnews.html' %}
            {% comment %} <div class="advertisement">
              <img src="{% static 'images/bill-hicks-mic-tap.gif' %}" class="img-fluid"/>
            </div> {% endcomment %}
            

          </div>

        </div>
      </div>
    </div>

    </section>




 {% comment %} Politics Section {% endcomment %}
 <section class="block2 py-2">
  <div class="container">
      <div class="items-content">
        {% if politics %}
        <div class="main-article">

          <h3 class="text-color">राजनीति</h3>
          <div class="first-news py-3 row row-cols-1 row-cols-sm-1 row-cols-md-2 row-cols-lg-3">
                  {% for rajniti in politics|slice:":6" %}

                  <div class="col">                                   
                    <div class="card common-card border-0">
                      <a href="{% url 'post:detail' rajniti.id %}" class="stretched-link"></a>
                      {% if rajniti.image %}

                      <img src="{{ rajniti.image.url }}" class="card-img-bottom card-img-size img-fluid" alt="{{rajniti.title}}">
                      {% endif %}
                      <div class="p-2">
                        <div class="card-title text-card">{{ rajniti.title }}</div>
                          <small class="text-muted">
                            {{ rajniti.created_at|nepalihumanize:86400 }}
                          </small>                     
                      </div>

                    </div>
                  
                  </div>
                  {% endfor %}
                  
           </div>
                
                
        </div>
              {% endif %}
        <div class="side-news common-ads ">
          {% comment %} <div class="advertisement mb-4">
            <img src="{% static 'images/bill-hicks-mic-tap.gif' %}" class="img-fluid">
          </div>
          <div class="advertisement mb-4">
            <img src="{% static 'images/bill-hicks-mic-tap.gif' %}" class="img-fluid"/>
          </div>
          <div class="advertisement mb-4">
            <img src="{% static 'images/bill-hicks-mic-tap.gif' %}" class="img-fluid"/>
          </div> {% endcomment %}
          

        </div>

      </div>
  </div>

  </section>


 {% comment %} Politics Section Ends {% endcomment %}


 {% comment %} Laws Section{% endcomment %}
 <section class="block2 py-2">
  <div class="container">
      <div class="items-content box2">
        {% if laws %}
        <div class="main-article">

          <h3 class="text-color">कानुन</h3>
          <div class="first-news py-3 row row-cols-1 row-cols-sm-1 row-cols-md-2 row-cols-lg-3">
                  {% for law in laws|slice:":6" %}

                  <div class="col">                                   
                    <div class="card common-card border-0">
                      <a href="{% url 'post:detail' law.id %}" class="stretched-link"></a>
                      {% if law.image %}

                      <img src="{{ law.image.url }}" class="card-img-bottom card-img-size img-fluid" alt="{{law.title}}">
                      {% endif %}
                      <div class="p-2">
                      <div class="card-title text-card">{{ law.title }}</div>
                      <small class="text-muted">
                        {{ law.created_at|nepalihumanize:86400 }}
                      </small>
                      </div>

                  </div>
                  
                </div>
                  {% endfor %}
                  
              </div>
                
                
         </div>
              {% endif %}
        <div class="side-news common-ads px-2">
          {% comment %} <div class="advertisement mb-4">
            <img src="{% static 'images/bill-hicks-mic-tap.gif' %}" class="img-fluid">
          </div>
          <div class="advertisement mb-4">
            <img src="{% static 'images/bill-hicks-mic-tap.gif' %}" class="img-fluid"/>
          </div>
          <div class="advertisement mb-4">
            <img src="{% static 'images/bill-hicks-mic-tap.gif' %}" class="img-fluid"/>
          </div> {% endcomment %}
          

        </div>

      </div>
    </div>
  </div>

  </section>


 
{% comment %} Laws Section Ends{% endcomment %}




 {% comment %} Sports Section {% endcomment %}
 <section class="block2 py-2">
  <div class="container">
      <div class="items-content box2" id="itemcontent">
        {% if sports %}
        <div class="main-article">

          <h3 class="text-color">खेलकुद</h3>
          <div class="first-news py-3 row row-cols-1 row-cols-sm-1 row-cols-md-2 row-cols-lg-3">
                  {% for sport in sports|slice:":6" %}

                  <div class="col">                                   
                    <div class="card common-card border-0">
                      <a href="{% url 'post:detail' sport.id %}" class="stretched-link"></a>
                      {% if sport.image %}
                      <img src="{{ sport.image.url }}" class="card-img-bottom card-img-size img-fluid" alt="{{sport.title}}">
                      {% endif %}
                      <div class="p-2">
                      <div class="card-title text-card">{{ sport.title }}</div>
                      <small class="text-muted">
                        {{ sport.created_at|nepalihumanize:86400 }}
                      </small>
                      </div>

                  </div>
                  
                </div>
                  {% endfor %}
                  
                </div>
                
                
              </div>
              {% endif %}
        <div class="side-news common-ads px-2">
          {% comment %} <div class="advertisement mb-4">
            <img src="{% static 'images/bill-hicks-mic-tap.gif' %}" class="img-fluid">
          </div>
          <div class="advertisement mb-4">
            <img src="{% static 'images/bill-hicks-mic-tap.gif' %}" class="img-fluid"/>
          </div>
          <div class="advertisement mb-4">
            <img src="{% static 'images/bill-hicks-mic-tap.gif' %}" class="img-fluid"/>
          </div> {% endcomment %}
          

        </div>

      </div>
    </div>
  </div>

  </section>


 {% comment %} Sports Section Ends {% endcomment %}

 
 {% comment %} Education Section {% endcomment %}
 <section class="block2 py-2">
   <div class="container">
     <div class="items-content box2">
        {% if education %}
        <div class="main-article">

          <h3 class="text-color">शिक्षा</h3>
          <div class="first-news py-3 row row-cols-1 row-cols-sm-1 row-cols-md-2 row-cols-lg-3">
                  {% for edu in education|slice:":6" %}

                  <div class="col">                                   
                    <div class="card common-card border-0">
                      <a href="{% url 'post:detail' edu.id %}" class="stretched-link"></a>
                      {% if edu.image %}
                      <img src="{{ edu.image.url }}" class="card-img-bottom card-img-size img-fluid" alt="{{edu.title}}">
                      {% endif %}
                      <div class="p-2">
                      <div class="card-title text-card">{{ edu.title }}</div>
                      <small class="text-muted">
                        {{ edu.created_at|nepalihumanize:86400 }}
                      </small>
                      </div>

                  </div>
                  
                </div>
                  {% endfor %}
                  
                </div>
                
                
              </div>
              {% endif %}
        <div class="side-news common-ads px-2">
          {% comment %} <div class="advertisement mb-4">
            <img src="{% static 'images/bill-hicks-mic-tap.gif' %}" class="img-fluid">
          </div>
          <div class="advertisement mb-4">
            <img src="{% static 'images/bill-hicks-mic-tap.gif' %}" class="img-fluid"/>
          </div>
          <div class="advertisement mb-4">
            <img src="{% static 'images/bill-hicks-mic-tap.gif' %}" class="img-fluid"/>
          </div>
           {% endcomment %}

        </div>

      </div>
    </div>
  </div>

  </section>


 {% comment %} Politics Section Ends {% endcomment %}


</div>




{% endblock maincontent %}