erastriya/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
# from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('auth/', include('django.contrib.auth.urls')),  # include auth URLs
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('',include('home.urls', namespace="home")),
    path('post/',include('post.urls',namespace="post")),
    # path('sitemap.xml/', serve, {'document_root': settings.STATICFILES_DIRS[0], 'path': 'sitemap.xml'}),
    # path('robots.txt/', serve, {'document_root': settings.STATICFILES_DIRS[0], 'path': 'robots.txt'}),



]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home.views import home_page,about_view,contact_view,advertisement_view
app_name = "home"
urlpatterns = [
    path('',home_page,name="home_page"),
    path('about/',about_view,name="about"),
    path('contact/',contact_view,name="contact"),
    path('advertisement-info/',advertisement_view,name="advertisement_info"),
]

post/urls.py
from django.urls import path
from post.views import (
    politics_view, news_view, law_view, sports_view, 
    education_view, detail_view, search_result,
    other_view, international_view, business_view,
    scienceandtech_view, entertainment_view, economy_view, 
    literature_view, religion_culture_view, capital_market_view
    
)

app_name = "post"
urlpatterns = [
    path('politics/',politics_view,name="politics"),
    path('news/',news_view,name="news"),
    path('law/',law_view,name="law"),
    path('sports/',sports_view,name="sports"),
    path('education/',education_view,name="education"),
    path('international/',international_view,name="international"),
    path('business/',business_view,name="business"),
    path('economy/',economy_view,name="economy"),
    path('entertainment/',entertainment_view,name="entertainment"),
    path('science-technology/',scienceandtech_view,name="scienceandtech"),
    path('literature/',literature_view,name="literature"),
    path('religion-culture/',religion_culture_view,name="religion_culture"),
    path('capital-market/',capital_market_view,name="capital_market"),
    path('post-detail/<int:id>/',detail_view,name="detail"),
    path('search/',search_result,name="search_result"),

    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="baseUrl" content="https://www.erastriya.com">
       <meta name="publisher" content="erastriya">
    </meta>   
    <title>
        {% block title %}
         ERastriya
        {% endblock title %}
    </title>
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'fav/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'fav/site.webmanifest' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
       <!-- Define a block for meta tags -->
       {% block meta_tags %}
       {% endblock %}
    {% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/bs.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.scss' %}">
    <link rel="stylesheet" href="{% static 'css/style.css.map' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
    {% endblock stylesheet %}
    <script type="text/javascript" src="https://platform-api.sharethis.com/js/sharethis.js#property=6480a747cc05f10013916a63&product=inline-share-buttons&source=platform" async="async"></script>  
    <!-- Google tag (gtag.js) -->
    <link rel="canonical" href="https://erastriya.com/">
<script async src="https://www.googletagmanager.com/gtag/js?id=G-LLQG9F1SNL"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-LLQG9F1SNL');
</script>
 </head>
    {% comment %} <script type="text/javascript" src="https://platform-api.sharethis.com/js/sharethis.js#property=6458cab31b837f0019d42081&product=inline-share-buttons&source=platform" async="async"></script></head> {% endcomment %}
<body>
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v16.0" nonce="kP8lYj67" referrerPolicy="strict-origin-when-cross-origin"></script>

    {% block content %}
    {% endblock content %}
    {% block script %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bs.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>

    <script src="{% static 'js/user.js' %}"></script>
    <script src="{% static 'js/post_detail.js' %}"></script>



    {% endblock script %}

</body>
</html>

templates/base_html.html
{% extends 'base.html' %}
{% block content %}
{% include 'navbar.html' %}
{% block maincontent %}

{% endblock maincontent %}
{% include 'footer.html' %}
{% endblock content %}

templates/footer.html
<!-- footer part start from here -->
{% load static %}

<section class="mt-2">


  <footer class="text-start text-gray text-lg-start bg-white">

    <!-- Grid container -->
    <section class="container">
      <!--Grid row-->
      <div class="row mt-3">
        <!--Grid column-->
        <div class="col-lg-4 col-md-12 col-sm-12 mb-4 mb-md-0 pr-4 ml-2">
          <div class="bg-white logo-footer">
            <img
              src="{% static 'images/logo.png' %}"
              alt="erastriya logo"
              loading="lazy"
            />
          </div>
  
          <div
            class="ml-4 footer-about lh-base text-secondary text-start"
          >
            <p class="mb-0">Erastriya Media House</p>
            <p class="mb-0">प्रेस काउन्सिल दर्ता नम्बर 4643-2080/081 A</p>
            <p class="mb-0">सूचना विभाग दर्ता नम्बर 4651-2081/82</p>
            <p class="mb-0">Anamnagar,Kathmandu</p>
            <p class="mb-0">Email:erastriyamediahouse1@gmail.com</p>
          </div>
          {% comment %}
          <hr />
          {% endcomment %}
  
          <ul
            class="d-flex  align-items-start color-secondary text-start footer-social-logo"
          >
  
          <li> <a type="button" href="https://www.facebook.com/profile.php?id=100070096502446"><i class="bi bi-facebook fs-3 fs-md-1 fs-lg-2"></i></a></li>
          <li> <a type="button" href="https://instagram.com/erastriya?igshid=NGExMmI2YTkyZg=="><i class="bi bi-instagram fs-3 fs-md-1 fs-lg-2"></i></a></li>
          <li> <a type="button" href="https://youtube.com/@bollywoodjukebox65?si=p9bwXlVL-EdAjijm"><i class="bi bi-youtube fs-3 fs-md-1 fs-lg-2"></i></a></li>
          <li> <a type="button" href="https://twitter.com/erastriya?t=pqlC1lnpFObDPqLi5ZbT8A&s=09"><i class="bi bi-twitter fs-3 fs-md-1 fs-lg-2"></i></a></li>
            <!-- Facebook -->
  
          </ul>
        </div>
        <!--Grid column-->
  
        
        <div class="col-lg-8 col-md-12 col-sm-12 mb-4 row pl-3">
          <div class="col-lg-4 col-md-4 col-sm-12 mb-md-0 text-start">
            <h5 class="text-uppercase mb-1 pb-1 footer-text-color">
              Quick Links
            </h5>
  
            <ul class="quick-links-ul text-secondary">
              <li class="mb-1">
                <a href="/"
                ><span class="footer-links">Home</span></a
              >            </li>
              <li class="mb-1">
                <a href="{% url 'home:about' %}"
                  ><span class="footer-links">About Us</span></a
                >
              </li>
              <li class="mb-1">
                <a href="{% url 'home:advertisement_info' %}"
                  ><span class="footer-links">Advertisement</span></a
                >
              </li>
              <li class="mb-1">
                <a href="{% url 'home:contact' %}"
                ><span class="footer-links">Contact Us</span></a
              >            </li>
            </ul>
          </div>
          <div class="col-lg-8 col-md-8 col-sm-12 mb-4 mb-md-0 text-start ">
            <h5 class="text-uppercase mb-1 footer-text-color">Our Team</h5>
  
            <div class="d-flex flex-column">
              <div class="d-flex justify-content-between footer-team-partition">
                <div class="text-start footer-team">
                  <span class="text-secondary">Founder</span>
                  <p class="fw-bolder">Bhairab Bahadur Rana</p>
                </div>
                <div class="text-start footer-team">
                  <span class="text-secondary">Editor</span>
                  <p class="fw-bolder">Rabi Rimal</p>
                </div>
              </div>
  
              <div class="d-flex justify-content-between footer-team-partition">
                <div class="text-start footer-team">
                  <span class="text-secondary">Multimedia</span>
                  <p class="fw-bolder">Harish Bahadur Rana</p>
                </div>
                <div class="text-start footer-team">
                  <span class="text-secondary">Reporter</span>
                  <p class="fw-bolder">Sujan Sarki</p>
                </div>
              </div>
  
              <div class="d-flex justify-content-between footer-team-partition">
                <div class="text-start footer-team">
                  <span class="text-secondary">Marketing</span>
                  <p class="fw-bolder">Shailendra Dhuwadi</p>
                </div>
                <div class="text-start footer-team">
                  <span class="text-secondary">IT Support</span>
                  <p class="fw-bolder">Arjun Uchai</p>
                </div>
              </div>
            </div>
          </div>
        </div>
  
    
  
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </section>
    <!-- Grid container -->
  
    <!-- Copyright -->
    <section class="text-center p-3 footer-bottom">
      © 2023 Copyright:
      <a class="text-white text-decoration-none pointer-event" href="https://erastriya.com/">ERastriya.com</a>
    </section>
    <!-- Copyright -->
  </footer>
  

</section>

<!-- End of .container -->

 <!-- end of footer -->

templates/navbar.html
{% load static %}
<!-- top part -->
<div class="top text-light">
  <div class="container flex">
    <div class="date">
      <iframe
        scrolling="no"
        border="0"
        frameborder="0"
        marginwidth="0"
        marginheight="0"
        allowtransparency="true"
        src="https://www.ashesh.com.np/linknepali-time.php?time_only=no&font_color=ffffff&aj_time=yes&font_size=14&line_brake=0&api=502137n143"
        width="334"
        height="30"
        class="date_display"
      ></iframe>
    </div>
    <div class="social-icon">
      <ul>
        <li>
          <a href="https://youtube.com/@bollywoodjukebox65?si=p9bwXlVL-EdAjijm"><i class="bi bi-youtube"></i></a>
        </li>
        <li>
          <a href="https://www.facebook.com/profile.php?id=100070096502446"><i class="bi bi-facebook"></i></a>
        </li>
        <li>
          <a href="https://www.whatsapp.com/"><i class="bi bi-whatsapp"></i></a>
        </li>
        <li> 
          <a href="https://instagram.com/erastriya?igshid=NGExMmI2YTkyZg=="><i class="bi bi-instagram"></i></a>
        </li>

      </ul>
    </div>
  </div>
</div>

<!-- logo and first ad section -->
<header>
  <div class="container flex">
    <div class="logo my-2">
      <a href ="/"><img src="{% static 'images/logo.png' %}" alt="Erastriya"/></a>
    </div>
    {% comment %} <div class="ads py">
      <img src="{% static 'images/add.gif' %}" />
    </div> {% endcomment %}
  </div>
</header>

<!-- Navigation -->
<nav id="nav-bar">
  <div class="container">
    <div class="nav nav_bar" id="nav">
      <div class="close-btn" id="close-btn">
        <i
          class="fa-solid fa-xmark"
          style="color: #ffffff"
          onclick="closeNav()"
        ></i>
      </div>
      <ul class="my-2">
        <li>
          <a href="/"><i class="fa fa-home" aria-hidden="true"></i>गृहपृष्ट</a>
        </li>
        <li><a href="{% url 'post:news' %}">समाचार </a></li>
        <li><a href="{% url 'post:politics' %}">राजनीति </a></li>
        <li><a href="{% url 'post:law' %}">कानुन </a></li>
        <li><a href="{% url 'post:sports' %}">खेलकुद </a></li>
        <li><a href="{% url 'post:education' %}">शिक्षा </a></li>
     
        <li>
          <div class="dropdown-btn">
            <button class="dropbtn" id="dropbtn">
              अन्य
              <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content" id="myDropdown">
              <a href="{% url 'post:international' %}">अन्तर्राष्ट्रिय
              </a>
              <a href="{% url 'post:scienceandtech' %}">बिज्ञान तथा प्रबिधि</a>
              <a href="{% url 'post:business' %}">ब्यापार</a>
              <a href="{% url 'post:entertainment' %}">मनोरञ्जन</a>
              <a href="{% url 'post:economy' %}">अर्थ/बाणिज्य</a>
              <a href="{% url 'post:literature' %}">साहित्य</a>
              <a href="{% url 'post:religion_culture' %}">धर्म/संस्कृति</a>
              <a href="{% url 'post:capital_market' %}">पूँजी बजार</a>



            </div>
          </div>
        </li>
      </ul>
      <!-- User module -->
      <div id="user">
        <div class="my-2 px-3">
          <form
            class="form-inline my-2 my-lg-0 d-flex"
            action="{% url 'post:search_result' %}"
          >
            <input
              class="form-control mr-sm-2 form-group-sm"
              type="search"
              placeholder="Search"
              aria-label="Search"
              name="q"
            />
            <button class="btn my-2 my-sm-0 search-btn" type="submit">
              <i class="mr-0 fa-solid fa-magnifying-glass" style="color: #ffffff;"></i>
              
            </button>
          </form>
        </div>
      </div>
    </div>
    <div class="toggle-button m-2 pt-2 toggle">
      <i class="fa-solid fa-bars" style="color: #ffffff"></i>
    </div>
  </div>
</nav>